branches:
  only:
    - master
    - dev

sudo: required

before_install:
  - docker build -t chisubmit .

script:
  - docker run chisubmit-app python runtests.py all
  - docker run chisubmit-app python runtests.py complete
